import type { Metadata } from "next";
import { Google_Sans } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Header from "./components/header";
import Sidebar from "./components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const ggogleSans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ggogleSans.variable} antialiased`}>
        <div className="flex h-screen">
          <Sidebar />
          <div className="w-full h-screen flex flex-col">
            <Header />
            <div className="grow border-y border-y-neutral-200 bg-neutral-100 flex justify-center items-center">
              {children}
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
