import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Header from "./components/header";
import Sidebar from "./components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const archivo = Archivo({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-archivo",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.className} antialiased`}>
        <div className="flex h-screen">
          <Sidebar />
          <div className="w-full h-screen flex flex-col">
            <Header />
            <div className="grow border-y border-y-neutral-200 bg-neutral-100 flex p-6 justify-center overflow-y-scroll no-scrollbar">
              {children}
            </div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
